# Generated by Django 4.2.4 on 2023-08-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0002_alter_budget_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="endDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="startDate",
            field=models.DateField(null=True),
        ),
    ]
