# Generated by Django 4.2.4 on 2023-09-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0005_budget_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="left",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="budget",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="budget",
            name="spent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
