# Generated by Django 4.2.4 on 2023-09-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0003_bill_ispaid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="recurring",
            field=models.CharField(
                choices=[
                    ("no", "No"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("annually", "Annually"),
                ],
                default="no",
                max_length=8,
            ),
        ),
    ]
