# Generated by Django 4.2.4 on 2023-09-23 18:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0003_budget_enddate_budget_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
