# Generated by Django 4.2.4 on 2023-10-03 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgets", "0008_alter_budget_amount_alter_budget_left_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
