# Generated by Django 4.2.4 on 2023-09-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_alter_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(max_length=300),
        ),
    ]
