# Generated by Django 4.2.4 on 2023-09-24 19:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0005_remove_transaction_category_transaction_budget_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
    ]
