# Generated by Django 4.2.4 on 2023-10-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0005_bill_user"),
        ("transactions", "0007_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bills.bill",
            ),
        ),
    ]
