# Generated by Django 4.2.4 on 2023-09-26 01:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saving",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="saving",
            name="left",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="saving",
            name="percent_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="saving",
            name="saved",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="saving",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="saving",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
