# Generated by Django 4.2.4 on 2023-09-26 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0002_saving_amount_saving_left_saving_percent_completed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saving",
            old_name="percent_completed",
            new_name="percentage",
        ),
    ]
