# Generated by Django 4.2.4 on 2023-09-26 20:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0003_rename_percent_completed_saving_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="saving",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
