# Generated by Django 4.2.4 on 2023-10-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0005_saving_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="saving",
            name="selected",
            field=models.BooleanField(default=False),
        ),
    ]
