# Generated by Django 4.2.4 on 2023-09-23 18:33

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0005_budget_color"),
        ("transactions", "0004_alter_transaction_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="budgets.budget",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
